name: Build
on: push

jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        project: ["WeSplit", "Exchange", "GuessTheFlag", "ViewsAndModifiers", "RockPaperScissors", "BetterRest", "WordScramble", "Animations", "Multiply", "iExpense", "Moonshot", "Drawing"]
    steps:
    - name: Checkout project  
      uses: actions/checkout@v1
    - name: Build the application
      run: |
        sudo xcode-select -s /Applications/Xcode_11.app
        set -o pipefail && xcodebuild -project ${{matrix.project}}/${{matrix.project}}.xcodeproj -scheme ${{matrix.project}} -destination "platform=iOS Simulator,name=iPhone 11 Pro" | xcpretty --color --simple
